repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.3.0
        hooks:
            -   id: trailing-whitespace
            -   id: end-of-file-fixer
            -   id: check-yaml

    -   repo: https://github.com/psf/black
        rev: 22.10.0
        hooks:
            -   id: black

    -   repo: https://github.com/pycqa/isort
        rev: 5.10.1
        hooks:
            -   id: isort
                name: isort

    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: 'tags/v0.982'  # Use the sha / tag you want to point at
        hooks:
            -   id: mypy
                additional_dependencies:
                    - types-requests

    -   repo: local
        hooks:
            -   id: pylint
                name: pylint
                entry: pylint
                language: system
                types: [ python ]
                args:
                  [
                      "-rn", # Only display messages
                      "-sn", # Don't display the score
                  ]
